name: NextVote
main: com.github.calenria.nextvote.NextVote
version: 0.5
website: https://github.com/Calenria/NextVote
author: Calenria
description: NextVotes!
database: true
depend: [Votifier, Vault, WorldEdit]
             
